# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql-server
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - some-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - some-network
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.docker.localhost`)"
      - "traefik.port=8081"
    depends_on:
      - db
      - reverse-proxy

  reverse-proxy:
    image: traefik:v2.10

    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
    networks:
      - some-network

networks:
  some-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
    name: mysql-volume
